#+TITLE: geoff.org --- My personal GNU Emacs config
#+DATE: <2017-07-01 Sat>
#+AUTHOR: Geoff Wark
#+EMAIL: gtw@airmail.cc

* First Things First
** Let Emacs know who I am

Be sure to change this to your own info ;)

#+BEGIN_SRC emacs-lisp
  (setq user-full-name    "Geoff Wark"
        user-mail-address "gtw@airmail.cc")
#+END_SRC

** Move the =custom-file=

Save customizations to their own file.  This prevents junk from being being appended to [[file:init.el][init.el]].

#+BEGIN_SRC emacs-lisp
  (setq custom-file "~/.emacs.d/custom.el")
  (load custom-file :noerror) ; we don't care if the file exists
#+END_SRC

** Keep all backups/auto-saves in =$TMPDIR=

#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist
        `((".*" . ,temporary-file-directory)))
  (setq auto-save-file-name-transforms
        `((".*" ,temporary-file-directory t)))
#+END_SRC

* =use-package= settings

Always install packages automatically if they are not already present on the system.

#+BEGIN_SRC emacs-lisp
  (setq use-package-always-ensure t)
#+END_SRC

* UI/UX
** Free up screen real estate

The following toolbars take up unnecessary space:

#+BEGIN_SRC emacs-lisp
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
#+END_SRC

** Theme

[[http://kippura.org/zenburnpage/][Zenburn]] is pretty easy on the eyes.

#+BEGIN_SRC emacs-lisp
  (use-package zenburn-theme
    :init
    (load-theme 'zenburn t))
#+END_SRC

** Face

Italicize comments.

#+BEGIN_SRC emacs-lisp
  (make-face-italic 'font-lock-comment-face)
#+END_SRC

Make =region= color more obvious.

#+BEGIN_SRC emacs-lisp
  (set-face-attribute 'region nil
                      :background "white smoke"
                      :foreground "black")
#+END_SRC

** Cursor

Make cursor easier to see by changing its color to red.

#+BEGIN_SRC emacs-lisp
  (add-to-list 'default-frame-alist '(cursor-color . "red"))
#+END_SRC

Also stop that goddamn blinking!

#+BEGIN_SRC emacs-lisp
  (blink-cursor-mode -1)
#+END_SRC

** Font

[[https://pagure.io/liberation-fonts][Liberation Fonts]] are pretty dope.  Make sure you have them installed.

#+BEGIN_SRC emacs-lisp
  (add-to-list 'default-frame-alist '(font . "Liberation Mono-12"))
#+END_SRC

* Indentation

Use spaces over tabs.  If needed you can insert a tab with =C-q TAB=

#+BEGIN_SRC emacs-lisp
  (setq-default indent-tabs-mode nil)
#+END_SRC

Default to using a width of 2 per indent column.

#+BEGIN_SRC emacs-lisp
  (setq-default tab-width 2)
#+END_SRC

* Sane Defaults

https://github.com/magnars/.emacs.d/blob/master/settings/sane-defaults.el

#+BEGIN_SRC emacs-lisp
  ;; Auto refresh buffers
  (global-auto-revert-mode 1)

  ;; Show keystrokes in progress
  (setq echo-keystrokes 0.1)

  ;; Move files to trash when deleting
  (setq delete-by-moving-to-trash t)

  ;; Real emacs knights don't use shift to mark things
  (setq shift-select-mode nil)

  ;; Answering just 'y' or 'n' will do
  (defalias 'yes-or-no-p 'y-or-n-p)

  ;; UTF-8 please
  (setq locale-coding-system 'utf-8) ; pretty
  (set-terminal-coding-system 'utf-8) ; pretty
  (set-keyboard-coding-system 'utf-8) ; pretty
  (set-selection-coding-system 'utf-8) ; please
  (prefer-coding-system 'utf-8) ; with sugar on top

  ;; Remove text in active region if inserting text
  (delete-selection-mode 1)

  ;; Always display column numbers
  (setq column-number-mode t)

  ;; Undo/redo window configuration with C-c <left>/<right>
  (winner-mode 1)

  ;; Show me empty lines after buffer end
  (set-default 'indicate-empty-lines t)

  ;; Easily navigate sillycased words
  (global-subword-mode 1)

  ;; Don't break lines for me, please
  (setq-default truncate-lines t)

  ;; Allow recursive minibuffers
  (setq enable-recursive-minibuffers t)

  ;; Sentences do not need double spaces to end. Period.
  (set-default 'sentence-end-double-space nil)

  ;; 80 chars is a good width.
  (set-default 'fill-column 80)
#+END_SRC

https://github.com/danielmai/.emacs.d/blob/master/config.org

#+BEGIN_SRC emacs-lisp
  (show-paren-mode t)

  ;; Don't beep at me
  (setq visible-bell t)
#+END_SRC

Highlight current line.

#+BEGIN_SRC emacs-lisp
  (global-hl-line-mode t)
#+END_SRC

